/**
 * LIGAREGISTER — GENERERAD FIL, REDIGERA INTE FÖR HAND.
 * =============================================================================
 * Genererad av scripts/generate-league-registry.ts ur den faktiska datan i
 * player_career_stint. Kör om scriptet när nya ligor dyker upp i importen.
 *
 * Registret finns för att inget liga-id någonsin ska skrivas för hand igen.
 * I den första versionen av config.ts var tre av tolv uteslutna cup-id gissade,
 * och två av dem pekade i själva verket på riktiga ligor (290 = Persian Gulf
 * Pro League, 169 = Super League) som därmed uteslöts av misstag.
 * league-registry.test.ts verifierar att varje id i config.ts matchar namnet
 * här, så samma sorts gissning inte kan smyga sig in igen.
 *
 * kind:
 *   "league"   — seriespel, kan få en koefficient
 *   "cup"      — blandar divisioner i samma tabell, aldrig med i ett betyg
 *   "friendly" — träningsmatcher, inte tävlingsspel
 *   "youth"    — ungdoms- och reservserier, en annan population
 *
 * Genererad 2026-08-23 ur 19252 karriärposter:
 * 238 serier, 112 cuper, 1 träningsmatchsformer, 4 ungdomsserier.
 */

export interface LeagueRegistryEntry {
  id: number;
  name: string;
  country: string | null;
  kind: "league" | "cup" | "friendly" | "youth";
  /** Totala minuter i vår data — visar vilka poster som faktiskt betyder något. */
  minutes: number;
}

export const LEAGUE_REGISTRY: readonly LeagueRegistryEntry[] = [
  { id: 2, name: "UEFA Champions League", country: "World", kind: "league", minutes: 141835 },
  { id: 3, name: "UEFA Europa League", country: "World", kind: "league", minutes: 271120 },
  { id: 11, name: "CONMEBOL Sudamericana", country: "World", kind: "league", minutes: 1326 },
  { id: 12, name: "CAF Champions League", country: "World", kind: "league", minutes: 2695 },
  { id: 13, name: "CONMEBOL Libertadores", country: "World", kind: "league", minutes: 2575 },
  { id: 14, name: "UEFA Youth League", country: "World", kind: "youth", minutes: 78 },
  { id: 15, name: "FIFA Club World Cup", country: "World", kind: "cup", minutes: 1284 },
  { id: 16, name: "CONCACAF Champions League", country: "World", kind: "league", minutes: 3972 },
  { id: 17, name: "AFC Champions League Elite", country: "World", kind: "league", minutes: 13786 },
  { id: 18, name: "AFC Champions League Two", country: "World", kind: "league", minutes: 5052 },
  { id: 20, name: "CAF Confederation Cup", country: "World", kind: "cup", minutes: 1632 },
  { id: 26, name: "International Champions Cup", country: "World", kind: "cup", minutes: 257 },
  { id: 28, name: "SAFF Championship", country: "World", kind: "league", minutes: 0 },
  { id: 39, name: "Premier League", country: "England", kind: "league", minutes: 89092 },
  { id: 40, name: "Championship", country: "England", kind: "league", minutes: 151353 },
  { id: 41, name: "League One", country: "England", kind: "league", minutes: 44518 },
  { id: 42, name: "League Two", country: "England", kind: "league", minutes: 17465 },
  { id: 43, name: "National League", country: "England", kind: "league", minutes: 24023 },
  { id: 45, name: "FA Cup", country: "England", kind: "cup", minutes: 21220 },
  { id: 46, name: "EFL Trophy", country: "England", kind: "cup", minutes: 8168 },
  { id: 47, name: "FA Trophy", country: "England", kind: "cup", minutes: 2494 },
  { id: 48, name: "League Cup", country: "England", kind: "cup", minutes: 19771 },
  { id: 49, name: "National League - Play-offs", country: "England", kind: "league", minutes: 2704 },
  { id: 51, name: "National League - South", country: "England", kind: "league", minutes: 4148 },
  { id: 61, name: "Ligue 1", country: "France", kind: "league", minutes: 77414 },
  { id: 62, name: "Ligue 2", country: "France", kind: "league", minutes: 54200 },
  { id: 63, name: "Ligue 3", country: "France", kind: "league", minutes: 2908 },
  { id: 65, name: "Coupe de la Ligue", country: "France", kind: "league", minutes: 2526 },
  { id: 66, name: "Coupe de France", country: "France", kind: "league", minutes: 12281 },
  { id: 69, name: "National 2 - Group C", country: "France", kind: "league", minutes: 0 },
  { id: 70, name: "National 2 - Group D", country: "France", kind: "league", minutes: 4037 },
  { id: 71, name: "Serie A", country: "Brazil", kind: "league", minutes: 6409 },
  { id: 72, name: "Serie B", country: "Brazil", kind: "league", minutes: 7182 },
  { id: 73, name: "Copa Do Brasil", country: "Brazil", kind: "cup", minutes: 4765 },
  { id: 75, name: "Serie C", country: "Brazil", kind: "league", minutes: 5282 },
  { id: 76, name: "Serie D", country: "Brazil", kind: "league", minutes: 10584 },
  { id: 78, name: "Bundesliga", country: "Germany", kind: "league", minutes: 92939 },
  { id: 79, name: "2. Bundesliga", country: "Germany", kind: "league", minutes: 123764 },
  { id: 80, name: "3. Liga", country: "Germany", kind: "league", minutes: 23035 },
  { id: 81, name: "DFB Pokal", country: "Germany", kind: "cup", minutes: 17630 },
  { id: 84, name: "Regionalliga - Nord", country: "Germany", kind: "league", minutes: 262 },
  { id: 86, name: "Regionalliga - SudWest", country: "Germany", kind: "league", minutes: 2343 },
  { id: 87, name: "Regionalliga - West", country: "Germany", kind: "league", minutes: 197 },
  { id: 88, name: "Eredivisie", country: "Netherlands", kind: "league", minutes: 268036 },
  { id: 89, name: "Eerste Divisie", country: "Netherlands", kind: "league", minutes: 75841 },
  { id: 90, name: "KNVB Beker", country: "Netherlands", kind: "cup", minutes: 23431 },
  { id: 94, name: "Primeira Liga", country: "Portugal", kind: "league", minutes: 22169 },
  { id: 95, name: "Segunda Liga", country: "Portugal", kind: "league", minutes: 11400 },
  { id: 96, name: "Taça de Portugal", country: "Portugal", kind: "cup", minutes: 676 },
  { id: 97, name: "Taça da Liga", country: "Portugal", kind: "cup", minutes: 398 },
  { id: 98, name: "J1 League", country: "Japan", kind: "league", minutes: 41443 },
  { id: 99, name: "J2 League", country: "Japan", kind: "league", minutes: 14277 },
  { id: 100, name: "J3 League", country: "Japan", kind: "league", minutes: 2286 },
  { id: 101, name: "J-League Cup", country: "Japan", kind: "cup", minutes: 3272 },
  { id: 102, name: "Emperor Cup", country: "Japan", kind: "cup", minutes: 828 },
  { id: 103, name: "Eliteserien", country: "Norway", kind: "league", minutes: 645546 },
  { id: 104, name: "1. Division", country: "Norway", kind: "league", minutes: 224986 },
  { id: 105, name: "NM Cupen", country: "Norway", kind: "cup", minutes: 31869 },
  { id: 106, name: "Ekstraklasa", country: "Poland", kind: "league", minutes: 87304 },
  { id: 107, name: "I Liga", country: "Poland", kind: "league", minutes: 12339 },
  { id: 108, name: "Cup", country: "Poland", kind: "cup", minutes: 5464 },
  { id: 109, name: "II Liga - East", country: "Poland", kind: "league", minutes: 270 },
  { id: 110, name: "Premier League", country: "Wales", kind: "league", minutes: 5572 },
  { id: 112, name: "Welsh Cup", country: "Wales", kind: "cup", minutes: 540 },
  { id: 114, name: "Superettan", country: "Sweden", kind: "league", minutes: 2457829 },
  { id: 115, name: "Svenska Cupen", country: "Sweden", kind: "cup", minutes: 462548 },
  { id: 116, name: "Premier League", country: "Belarus", kind: "league", minutes: 9043 },
  { id: 117, name: "1. Division", country: "Belarus", kind: "league", minutes: 630 },
  { id: 119, name: "Superliga", country: "Denmark", kind: "league", minutes: 431164 },
  { id: 120, name: "1. Division", country: "Denmark", kind: "league", minutes: 160386 },
  { id: 121, name: "DBU Pokalen", country: "Denmark", kind: "cup", minutes: 73752 },
  { id: 122, name: "2. Division", country: "Denmark", kind: "league", minutes: 0 },
  { id: 128, name: "Liga Profesional Argentina", country: "Argentina", kind: "league", minutes: 955 },
  { id: 129, name: "Primera Nacional", country: "Argentina", kind: "league", minutes: 7919 },
  { id: 130, name: "Copa Argentina", country: "Argentina", kind: "cup", minutes: 1890 },
  { id: 131, name: "Primera B Metropolitana", country: "Argentina", kind: "league", minutes: 3847 },
  { id: 135, name: "Serie A", country: "Italy", kind: "league", minutes: 156951 },
  { id: 136, name: "Serie B", country: "Italy", kind: "league", minutes: 58782 },
  { id: 137, name: "Coppa Italia", country: "Italy", kind: "cup", minutes: 9324 },
  { id: 140, name: "La Liga", country: "Spain", kind: "league", minutes: 37238 },
  { id: 141, name: "Segunda División", country: "Spain", kind: "league", minutes: 39323 },
  { id: 143, name: "Copa del Rey", country: "Spain", kind: "cup", minutes: 7968 },
  { id: 144, name: "Jupiler Pro League", country: "Belgium", kind: "league", minutes: 131576 },
  { id: 145, name: "Challenger Pro League", country: "Belgium", kind: "league", minutes: 27673 },
  { id: 147, name: "Cup", country: "Belgium", kind: "cup", minutes: 21254 },
  { id: 162, name: "Primera División", country: "Costa-Rica", kind: "league", minutes: 14271 },
  { id: 164, name: "Úrvalsdeild", country: "Iceland", kind: "league", minutes: 226576 },
  { id: 165, name: "1. Deild", country: "Iceland", kind: "league", minutes: 10146 },
  { id: 167, name: "Cup", country: "Iceland", kind: "cup", minutes: 22622 },
  { id: 168, name: "League Cup", country: "Iceland", kind: "cup", minutes: 0 },
  { id: 169, name: "Super League", country: "China", kind: "league", minutes: 33942 },
  { id: 170, name: "League One", country: "China", kind: "league", minutes: 17658 },
  { id: 171, name: "FA Cup", country: "China", kind: "cup", minutes: 8860 },
  { id: 172, name: "First League", country: "Bulgaria", kind: "league", minutes: 39140 },
  { id: 173, name: "Second League", country: "Bulgaria", kind: "league", minutes: 885 },
  { id: 174, name: "Cup", country: "Bulgaria", kind: "cup", minutes: 3535 },
  { id: 179, name: "Premiership", country: "Scotland", kind: "league", minutes: 57952 },
  { id: 180, name: "Championship", country: "Scotland", kind: "league", minutes: 21 },
  { id: 181, name: "FA Cup", country: "Scotland", kind: "cup", minutes: 4084 },
  { id: 182, name: "Challenge Cup", country: "Scotland", kind: "cup", minutes: 103 },
  { id: 183, name: "League One", country: "Scotland", kind: "league", minutes: 168 },
  { id: 184, name: "League Two", country: "Scotland", kind: "league", minutes: 1356 },
  { id: 185, name: "League Cup", country: "Scotland", kind: "cup", minutes: 14138 },
  { id: 186, name: "Ligue 1", country: "Algeria", kind: "league", minutes: 0 },
  { id: 188, name: "A-League", country: "Australia", kind: "league", minutes: 29179 },
  { id: 192, name: "New South Wales NPL", country: "Australia", kind: "league", minutes: 0 },
  { id: 195, name: "Victoria NPL", country: "Australia", kind: "league", minutes: 545 },
  { id: 197, name: "Super League 1", country: "Greece", kind: "league", minutes: 98826 },
  { id: 198, name: "Football League", country: "Greece", kind: "league", minutes: 5160 },
  { id: 199, name: "Cup", country: "Greece", kind: "cup", minutes: 15148 },
  { id: 202, name: "Ligue 1", country: "Tunisia", kind: "league", minutes: 4015 },
  { id: 203, name: "Süper Lig", country: "Turkey", kind: "league", minutes: 148734 },
  { id: 204, name: "1. Lig", country: "Turkey", kind: "league", minutes: 38572 },
  { id: 205, name: "2. Lig", country: "Turkey", kind: "league", minutes: 16032 },
  { id: 206, name: "Türkiye Kupası", country: "Turkey", kind: "cup", minutes: 14610 },
  { id: 207, name: "Super League", country: "Switzerland", kind: "league", minutes: 45026 },
  { id: 208, name: "Challenge League", country: "Switzerland", kind: "league", minutes: 5691 },
  { id: 209, name: "Schweizer Cup", country: "Switzerland", kind: "cup", minutes: 7412 },
  { id: 210, name: "HNL", country: "Croatia", kind: "league", minutes: 34420 },
  { id: 211, name: "First NL", country: "Croatia", kind: "league", minutes: 3778 },
  { id: 212, name: "Cup", country: "Croatia", kind: "cup", minutes: 3172 },
  { id: 218, name: "Bundesliga", country: "Austria", kind: "league", minutes: 38992 },
  { id: 219, name: "2. Liga", country: "Austria", kind: "league", minutes: 3167 },
  { id: 220, name: "Cup", country: "Austria", kind: "cup", minutes: 3661 },
  { id: 223, name: "Regionalliga - West", country: "Austria", kind: "league", minutes: 828 },
  { id: 229, name: "Landesliga - Steiermark", country: "Austria", kind: "league", minutes: 0 },
  { id: 233, name: "Premier League", country: "Egypt", kind: "league", minutes: 6324 },
  { id: 234, name: "Liga Nacional", country: "Honduras", kind: "league", minutes: 4433 },
  { id: 235, name: "Premier League", country: "Russia", kind: "league", minutes: 74466 },
  { id: 236, name: "First League", country: "Russia", kind: "league", minutes: 3319 },
  { id: 237, name: "Cup", country: "Russia", kind: "cup", minutes: 3977 },
  { id: 242, name: "Liga Pro", country: "Ecuador", kind: "league", minutes: 3259 },
  { id: 244, name: "Veikkausliiga", country: "Finland", kind: "league", minutes: 270257 },
  { id: 245, name: "Ykkönen", country: "Finland", kind: "league", minutes: 27552 },
  { id: 246, name: "Suomen Cup", country: "Finland", kind: "cup", minutes: 35870 },
  { id: 247, name: "Kakkonen - Lohko A", country: "Finland", kind: "league", minutes: 199 },
  { id: 249, name: "Kakkonen - Lohko C", country: "Finland", kind: "league", minutes: 2566 },
  { id: 253, name: "Major League Soccer", country: "USA", kind: "league", minutes: 230755 },
  { id: 255, name: "USL Championship", country: "USA", kind: "league", minutes: 72909 },
  { id: 257, name: "US Open Cup", country: "USA", kind: "cup", minutes: 18151 },
  { id: 259, name: "Canadian Championship", country: "Canada", kind: "league", minutes: 1669 },
  { id: 261, name: "National Division", country: "Luxembourg", kind: "league", minutes: 4535 },
  { id: 262, name: "Liga MX", country: "Mexico", kind: "league", minutes: 7030 },
  { id: 263, name: "Liga de Expansión MX", country: "Mexico", kind: "league", minutes: 1804 },
  { id: 265, name: "Primera División", country: "Chile", kind: "league", minutes: 3951 },
  { id: 266, name: "Primera B", country: "Chile", kind: "league", minutes: 2768 },
  { id: 267, name: "Copa Chile", country: "Chile", kind: "cup", minutes: 267 },
  { id: 269, name: "Segunda División", country: "Uruguay", kind: "league", minutes: 1916 },
  { id: 270, name: "Primera División - Clausura", country: "Uruguay", kind: "league", minutes: 3905 },
  { id: 271, name: "NB I", country: "Hungary", kind: "league", minutes: 45372 },
  { id: 273, name: "Magyar Kupa", country: "Hungary", kind: "cup", minutes: 1965 },
  { id: 274, name: "Liga 1", country: "Indonesia", kind: "league", minutes: 19322 },
  { id: 278, name: "Super League", country: "Malaysia", kind: "league", minutes: 2404 },
  { id: 280, name: "Premiership", country: "New-Zealand", kind: "league", minutes: 1000 },
  { id: 281, name: "Primera División", country: "Peru", kind: "league", minutes: 8622 },
  { id: 283, name: "Liga I", country: "Romania", kind: "league", minutes: 5907 },
  { id: 284, name: "Liga II", country: "Romania", kind: "league", minutes: 1926 },
  { id: 285, name: "Cupa României", country: "Romania", kind: "cup", minutes: 847 },
  { id: 286, name: "Super Liga", country: "Serbia", kind: "league", minutes: 41367 },
  { id: 287, name: "Prva Liga", country: "Serbia", kind: "league", minutes: 8088 },
  { id: 288, name: "Premier Soccer League", country: "South-Africa", kind: "league", minutes: 18561 },
  { id: 289, name: "1st Division", country: "South-Africa", kind: "league", minutes: 0 },
  { id: 290, name: "Persian Gulf Pro League", country: "Iran", kind: "league", minutes: 11330 },
  { id: 292, name: "K League 1", country: "South-Korea", kind: "league", minutes: 29817 },
  { id: 293, name: "K League 2", country: "South-Korea", kind: "league", minutes: 21573 },
  { id: 294, name: "FA Cup", country: "South-Korea", kind: "cup", minutes: 1879 },
  { id: 296, name: "Thai League 1", country: "Thailand", kind: "league", minutes: 26406 },
  { id: 297, name: "Thai League 2", country: "Thailand", kind: "league", minutes: 0 },
  { id: 301, name: "Pro League", country: "United-Arab-Emirates", kind: "league", minutes: 8128 },
  { id: 302, name: "League Cup", country: "United-Arab-Emirates", kind: "cup", minutes: 0 },
  { id: 303, name: "Division 1", country: "United-Arab-Emirates", kind: "league", minutes: 0 },
  { id: 305, name: "Stars League", country: "Qatar", kind: "league", minutes: 18277 },
  { id: 306, name: "Second Division", country: "Qatar", kind: "league", minutes: 0 },
  { id: 307, name: "Pro League", country: "Saudi-Arabia", kind: "league", minutes: 22898 },
  { id: 308, name: "Division 1", country: "Saudi-Arabia", kind: "league", minutes: 0 },
  { id: 310, name: "Superliga", country: "Albania", kind: "league", minutes: 5 },
  { id: 311, name: "1st Division", country: "Albania", kind: "league", minutes: 0 },
  { id: 314, name: "Cup", country: "Bosnia", kind: "cup", minutes: 366 },
  { id: 315, name: "Premijer Liga", country: "Bosnia", kind: "league", minutes: 19816 },
  { id: 317, name: "1st League - RS", country: "Bosnia", kind: "league", minutes: 0 },
  { id: 318, name: "1. Division", country: "Cyprus", kind: "league", minutes: 102251 },
  { id: 319, name: "2. Division", country: "Cyprus", kind: "league", minutes: 0 },
  { id: 321, name: "Cup", country: "Cyprus", kind: "cup", minutes: 8685 },
  { id: 324, name: "I-League", country: "India", kind: "league", minutes: 3968 },
  { id: 327, name: "Erovnuli Liga", country: "Georgia", kind: "league", minutes: 15167 },
  { id: 329, name: "Meistriliiga", country: "Estonia", kind: "league", minutes: 22282 },
  { id: 330, name: "Premier League", country: "Kuwait", kind: "league", minutes: 0 },
  { id: 332, name: "Super Liga", country: "Slovakia", kind: "league", minutes: 8006 },
  { id: 333, name: "Premier League", country: "Ukraine", kind: "league", minutes: 8387 },
  { id: 334, name: "Persha Liga", country: "Ukraine", kind: "league", minutes: 2060 },
  { id: 335, name: "Cup", country: "Ukraine", kind: "cup", minutes: 180 },
  { id: 337, name: "Druha Liga - Group B", country: "Ukraine", kind: "league", minutes: 1011 },
  { id: 338, name: "Primera Division", country: "Guatemala", kind: "league", minutes: 0 },
  { id: 340, name: "V.League 1", country: "Vietnam", kind: "league", minutes: 1568 },
  { id: 341, name: "Cup", country: "Vietnam", kind: "cup", minutes: 90 },
  { id: 342, name: "Premier League", country: "Armenia", kind: "league", minutes: 1514 },
  { id: 344, name: "Primera División", country: "Bolivia", kind: "league", minutes: 862 },
  { id: 345, name: "Czech Liga", country: "Czech-Republic", kind: "league", minutes: 32223 },
  { id: 347, name: "Cup", country: "Czech-Republic", kind: "cup", minutes: 3454 },
  { id: 357, name: "Premier Division", country: "Ireland", kind: "league", minutes: 26429 },
  { id: 358, name: "First Division", country: "Ireland", kind: "league", minutes: 406 },
  { id: 359, name: "FAI Cup", country: "Ireland", kind: "cup", minutes: 1000 },
  { id: 360, name: "League Cup", country: "Ireland", kind: "cup", minutes: 230 },
  { id: 362, name: "A Lyga", country: "Lithuania", kind: "league", minutes: 17328 },
  { id: 365, name: "Virsliga", country: "Latvia", kind: "league", minutes: 3642 },
  { id: 367, name: "Meistaradeildin", country: "Faroe-Islands", kind: "league", minutes: 23166 },
  { id: 368, name: "Premier League", country: "Singapore", kind: "league", minutes: 2506 },
  { id: 369, name: "Super League", country: "Uzbekistan", kind: "league", minutes: 550 },
  { id: 371, name: "First League", country: "Macedonia", kind: "league", minutes: 15243 },
  { id: 373, name: "1. SNL", country: "Slovenia", kind: "league", minutes: 22207 },
  { id: 374, name: "2. SNL", country: "Slovenia", kind: "league", minutes: 364 },
  { id: 375, name: "Cup", country: "Slovenia", kind: "cup", minutes: 2181 },
  { id: 380, name: "Premier League", country: "Hong-Kong", kind: "league", minutes: 3260 },
  { id: 382, name: "Liga Leumit", country: "Israel", kind: "league", minutes: 7433 },
  { id: 383, name: "Ligat Ha'al", country: "Israel", kind: "league", minutes: 40509 },
  { id: 384, name: "State Cup", country: "Israel", kind: "cup", minutes: 2947 },
  { id: 385, name: "Toto Cup Ligat Al", country: "Israel", kind: "cup", minutes: 2950 },
  { id: 386, name: "Ligue 1", country: "Ivory-Coast", kind: "league", minutes: 0 },
  { id: 389, name: "Premier League", country: "Kazakhstan", kind: "league", minutes: 8437 },
  { id: 393, name: "Premier League", country: "Malta", kind: "league", minutes: 1880 },
  { id: 394, name: "Super Liga", country: "Moldova", kind: "league", minutes: 4265 },
  { id: 398, name: "Premier League", country: "Bangladesh", kind: "league", minutes: 754 },
  { id: 408, name: "Premiership", country: "Northern-Ireland", kind: "league", minutes: 90 },
  { id: 419, name: "Premyer Liqa", country: "Azerbaijan", kind: "league", minutes: 22146 },
  { id: 420, name: "Cup", country: "Azerbaijan", kind: "cup", minutes: 2256 },
  { id: 436, name: "Primera División RFEF - Group 2", country: "Spain", kind: "league", minutes: 8544 },
  { id: 438, name: "Primera División RFEF - Group 4", country: "Spain", kind: "league", minutes: 453 },
  { id: 450, name: "Tercera División RFEF - Group 12", country: "Spain", kind: "league", minutes: 2647 },
  { id: 452, name: "Tercera División RFEF - Group 14", country: "Spain", kind: "league", minutes: 5061 },
  { id: 456, name: "Tercera División RFEF - Group 18", country: "Spain", kind: "league", minutes: 2181 },
  { id: 472, name: "National 3 - Group M", country: "France", kind: "league", minutes: 1495 },
  { id: 473, name: "2. Division - Group 1", country: "Norway", kind: "league", minutes: 5942 },
  { id: 474, name: "2. Division - Group 2", country: "Norway", kind: "league", minutes: 32984 },
  { id: 476, name: "Paulista - A2", country: "Brazil", kind: "league", minutes: 316 },
  { id: 477, name: "Gaúcho - 1", country: "Brazil", kind: "league", minutes: 585 },
  { id: 479, name: "Canadian Premier League", country: "Canada", kind: "league", minutes: 16732 },
  { id: 486, name: "Coppa", country: "Belarus", kind: "cup", minutes: 349 },
  { id: 487, name: "First Amateur Division", country: "Belgium", kind: "league", minutes: 5381 },
  { id: 488, name: "U19 Bundesliga", country: "Germany", kind: "youth", minutes: 1740 },
  { id: 489, name: "USL League One", country: "USA", kind: "league", minutes: 4444 },
  { id: 491, name: "Løgmanssteypid", country: "Faroe-Islands", kind: "league", minutes: 2996 },
  { id: 492, name: "Tweede Divisie", country: "Netherlands", kind: "league", minutes: 7000 },
  { id: 494, name: "Super League 2", country: "Greece", kind: "league", minutes: 85 },
  { id: 495, name: "Hazfi Cup", country: "Iran", kind: "cup", minutes: 0 },
  { id: 498, name: "Cup", country: "Kazakhstan", kind: "cup", minutes: 333 },
  { id: 500, name: "FA Cup", country: "Malaysia", kind: "cup", minutes: 0 },
  { id: 506, name: "2. liga", country: "Slovakia", kind: "league", minutes: 638 },
  { id: 507, name: "Cup", country: "South-Africa", kind: "cup", minutes: 1364 },
  { id: 508, name: "League Cup", country: "South-Africa", kind: "cup", minutes: 435 },
  { id: 509, name: "8 Cup", country: "South-Africa", kind: "cup", minutes: 469 },
  { id: 511, name: "Cup", country: "Tunisia", kind: "cup", minutes: 0 },
  { id: 519, name: "Super Cup", country: "Belgium", kind: "cup", minutes: 852 },
  { id: 522, name: "Amazonense", country: "Brazil", kind: "league", minutes: 0 },
  { id: 531, name: "UEFA Super Cup", country: "World", kind: "cup", minutes: 179 },
  { id: 533, name: "CAF Super Cup", country: "World", kind: "cup", minutes: 161 },
  { id: 539, name: "Super Cup", country: "Egypt", kind: "cup", minutes: 110 },
  { id: 542, name: "Iraqi League", country: "Iraq", kind: "league", minutes: 0 },
  { id: 543, name: "Super Cup", country: "Netherlands", kind: "cup", minutes: 95 },
  { id: 544, name: "FA Cup", country: "Hong-Kong", kind: "cup", minutes: 288 },
  { id: 547, name: "Super Cup", country: "Italy", kind: "cup", minutes: 540 },
  { id: 550, name: "Super Cup", country: "Portugal", kind: "cup", minutes: 0 },
  { id: 551, name: "Super Cup", country: "Turkey", kind: "cup", minutes: 0 },
  { id: 559, name: "League Cup", country: "Northern-Ireland", kind: "cup", minutes: 0 },
  { id: 560, name: "Presidents Cup", country: "United-Arab-Emirates", kind: "cup", minutes: 0 },
  { id: 563, name: "Ettan - Norra", country: "Sweden", kind: "league", minutes: 0 },
  { id: 564, name: "Ettan - Södra", country: "Sweden", kind: "league", minutes: 1048511 },
  { id: 567, name: "Ligi kuu Bara", country: "Tanzania", kind: "league", minutes: 0 },
  { id: 573, name: "Srpska Liga - Vojvodina", country: "Serbia", kind: "league", minutes: 0 },
  { id: 602, name: "Baiano - 1", country: "Brazil", kind: "league", minutes: 162 },
  { id: 603, name: "Paraibano", country: "Brazil", kind: "league", minutes: 148 },
  { id: 604, name: "Catarinense - 1", country: "Brazil", kind: "league", minutes: 2764 },
  { id: 605, name: "Paulista - A3", country: "Brazil", kind: "league", minutes: 454 },
  { id: 606, name: "Paranaense - 1", country: "Brazil", kind: "league", minutes: 811 },
  { id: 610, name: "Brasiliense", country: "Brazil", kind: "league", minutes: 0 },
  { id: 612, name: "Copa do Nordeste", country: "Brazil", kind: "cup", minutes: 290 },
  { id: 621, name: "Piauiense", country: "Brazil", kind: "league", minutes: 711 },
  { id: 624, name: "Carioca - 1", country: "Brazil", kind: "league", minutes: 1700 },
  { id: 626, name: "Sergipano", country: "Brazil", kind: "league", minutes: 385 },
  { id: 627, name: "Paraense", country: "Brazil", kind: "league", minutes: 379 },
  { id: 628, name: "Goiano - 1", country: "Brazil", kind: "league", minutes: 348 },
  { id: 629, name: "Mineiro - 1", country: "Brazil", kind: "league", minutes: 4306 },
  { id: 639, name: "Super Cup", country: "Iceland", kind: "cup", minutes: 0 },
  { id: 651, name: "Second League - Group 1", country: "Russia", kind: "league", minutes: 379 },
  { id: 653, name: "Second League - Group 4", country: "Russia", kind: "league", minutes: 1045 },
  { id: 655, name: "Copa Constitució", country: "Andorra", kind: "cup", minutes: 0 },
  { id: 656, name: "Super Cup", country: "Bulgaria", kind: "cup", minutes: 0 },
  { id: 657, name: "Cup", country: "Estonia", kind: "cup", minutes: 776 },
  { id: 658, name: "Cup", country: "Latvia", kind: "cup", minutes: 176 },
  { id: 661, name: "Cup", country: "Lithuania", kind: "cup", minutes: 1194 },
  { id: 664, name: "Superliga", country: "Kosovo", kind: "league", minutes: 0 },
  { id: 667, name: "Friendlies Clubs", country: "World", kind: "friendly", minutes: 7340 },
  { id: 672, name: "David Kipiani Cup", country: "Georgia", kind: "cup", minutes: 1066 },
  { id: 674, name: "Cupa", country: "Moldova", kind: "cup", minutes: 194 },
  { id: 677, name: "QSL Cup", country: "Qatar", kind: "cup", minutes: 767 },
  { id: 680, name: "Cup", country: "Slovakia", kind: "cup", minutes: 654 },
  { id: 692, name: "Primera División RFEF - Group 5", country: "Spain", kind: "league", minutes: 6490 },
  { id: 702, name: "Premier League 2 Division One", country: "England", kind: "league", minutes: 1187 },
  { id: 703, name: "Professional Development League", country: "England", kind: "league", minutes: 0 },
  { id: 705, name: "Campionato Primavera - 1", country: "Italy", kind: "youth", minutes: 5009 },
  { id: 707, name: "Cup", country: "Albania", kind: "cup", minutes: 0 },
  { id: 709, name: "Cup", country: "Armenia", kind: "cup", minutes: 195 },
  { id: 714, name: "Cup", country: "Egypt", kind: "cup", minutes: 70 },
  { id: 715, name: "DFB Junioren Pokal", country: "Germany", kind: "youth", minutes: 218 },
  { id: 716, name: "Senior Shield", country: "Hong-Kong", kind: "league", minutes: 514 },
  { id: 727, name: "Super Cup", country: "Poland", kind: "cup", minutes: 320 },
  { id: 732, name: "Cup", country: "Serbia", kind: "cup", minutes: 1207 },
  { id: 738, name: "League Cup", country: "Wales", kind: "cup", minutes: 90 },
  { id: 756, name: "Cup", country: "Macedonia", kind: "cup", minutes: 270 },
  { id: 757, name: "Irish Cup", country: "Northern-Ireland", kind: "cup", minutes: 90 },
  { id: 767, name: "CONCACAF League", country: "World", kind: "league", minutes: 1671 },
  { id: 772, name: "Leagues Cup", country: "World", kind: "cup", minutes: 4714 },
  { id: 774, name: "3. Division - Girone 1", country: "Norway", kind: "league", minutes: 0 },
  { id: 779, name: "3. Division - Girone 6", country: "Norway", kind: "league", minutes: 0 },
  { id: 802, name: "Cup", country: "Uzbekistan", kind: "cup", minutes: 126 },
  { id: 814, name: "Reykjavik Cup", country: "Iceland", kind: "cup", minutes: 1557 },
  { id: 824, name: "Emir Cup", country: "Qatar", kind: "cup", minutes: 1074 },
  { id: 825, name: "Qatar Cup", country: "Qatar", kind: "cup", minutes: 653 },
  { id: 827, name: "Crown Prince Cup", country: "Saudi-Arabia", kind: "cup", minutes: 0 },
  { id: 843, name: "Copa Verde", country: "Brazil", kind: "cup", minutes: 595 },
  { id: 848, name: "UEFA Europa Conference League", country: "World", kind: "league", minutes: 161757 },
  { id: 852, name: "Super Cup", country: "Cyprus", kind: "cup", minutes: 0 },
  { id: 865, name: "Liga 3", country: "Portugal", kind: "league", minutes: 0 },
  { id: 871, name: "Premier League Cup", country: "England", kind: "cup", minutes: 514 },
  { id: 874, name: "Australia Cup", country: "Australia", kind: "cup", minutes: 676 },
  { id: 879, name: "Segunda División RFEF - Group 5", country: "Spain", kind: "league", minutes: 5820 },
  { id: 885, name: "Campeones Cup", country: "World", kind: "cup", minutes: 0 },
  { id: 898, name: "League Cup", country: "Thailand", kind: "cup", minutes: 1336 },
  { id: 899, name: "League Cup", country: "Finland", kind: "cup", minutes: 14235 },
  { id: 909, name: "MLS Next Pro", country: "USA", kind: "league", minutes: 1109 },
  { id: 937, name: "Emirates Cup", country: "World", kind: "cup", minutes: 0 },
  { id: 943, name: "Serie C - Girone C", country: "Italy", kind: "league", minutes: 1903 },
  { id: 959, name: "Cup", country: "Singapore", kind: "cup", minutes: 875 },
  { id: 974, name: "Serie C - Supercoppa Lega Finals", country: "Italy", kind: "cup", minutes: 3391 },
  { id: 977, name: "Tercera División RFEF - Promotion - Play-offs", country: "Spain", kind: "league", minutes: 16288 },
  { id: 984, name: "National League - North - Play-offs", country: "England", kind: "league", minutes: 4896 },
  { id: 985, name: "National League - South - Play-offs", country: "England", kind: "league", minutes: 6999 },
  { id: 1000, name: "Segunda División RFEF - Play-offs", country: "Spain", kind: "league", minutes: 11621 },
  { id: 1003, name: "Regionalliga - Relegation Round", country: "Germany", kind: "league", minutes: 2332 },
  { id: 1004, name: "Derde Divisie - Relegation Round", country: "Netherlands", kind: "league", minutes: 0 },
  { id: 1006, name: "Primera División RFEF - Play Offs", country: "Spain", kind: "league", minutes: 15583 },
  { id: 1022, name: "Premier League - Summer Series", country: "England", kind: "league", minutes: 473 },
  { id: 1028, name: "CONCACAF Central American Cup", country: "World", kind: "cup", minutes: 1074 },
  { id: 1029, name: "National 3 - Group G", country: "France", kind: "league", minutes: 0 },
  { id: 1043, name: "African Football League", country: "World", kind: "league", minutes: 2 },
  { id: 1052, name: "Kakkonen - Play-offs", country: "Finland", kind: "league", minutes: 0 },
  { id: 1053, name: "Division 2 - Play-offs", country: "Sweden", kind: "league", minutes: 0 },
  { id: 1054, name: "2. Division - Play-offs", country: "Norway", kind: "league", minutes: 1444 },
  { id: 1055, name: "Ettan - Relegation Round", country: "Sweden", kind: "league", minutes: 511418 },
  { id: 1056, name: "National League - Championship - Final", country: "New-Zealand", kind: "league", minutes: 3504 },
  { id: 1087, name: "Ykkösliiga", country: "Finland", kind: "league", minutes: 5756 },
  { id: 1089, name: "UAE-Qatar - Super Shield", country: "World", kind: "league", minutes: 90 },
  { id: 1095, name: "USL League One Cup", country: "USA", kind: "cup", minutes: 513 },
  { id: 1132, name: "AFC Challenge League", country: "World", kind: "league", minutes: 224 },
  { id: 1156, name: "National League Cup", country: "England", kind: "cup", minutes: 722 },
  { id: 1168, name: "FIFA Intercontinental Cup", country: "World", kind: "cup", minutes: 885 },
];

const BY_ID = new Map(LEAGUE_REGISTRY.map((l) => [l.id, l]));

export function lookupLeague(id: number): LeagueRegistryEntry | undefined {
  return BY_ID.get(id);
}

/** Turneringar som aldrig får bidra till ett betyg, oavsett koefficient. */
export function isCompetitiveLeague(id: number): boolean {
  return BY_ID.get(id)?.kind === "league";
}
